accounts/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from jobsapp.views import EditProfileView
from .views import *

app_name = "accounts"

urlpatterns = [
    path('employee/register', RegisterEmployeeeView.as_view(), name='employee-register'),
    path('employer/register', RegisterEmployeerView.as_view(), name='employer-register'),
    path('employee/profile/update', EditProfileView.as_view(), name='employer-profile-update'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),
    path('', include('personality.urls')), 
    path('', include('recognition.urls')),
]

jobsapp/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "jobs"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='search'),
    path('employer/dashboard', include([
        path('', DashboardView.as_view(), name='employer-dashboard'),
        path('all-applicants', ApplicantsListView.as_view(), name='employer-all-applicants'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='employer-dashboard-applicants'),
        path('mark-filled/<int:job_id>', filled, name='job-mark-filled'),
        path('delete/<int:job_id>', delete, name='job-delete'),
    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs', JobListView.as_view(), name='jobs'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('employer/jobs/create', JobCreateView.as_view(), name='employer-jobs-create'),
    path('employer/jobs/edit/<int:pk>', JobUpdateView.as_view(), name='employer-jobs-update'),
    path('upload/', upload_document, name='upload_document'),
    path('about', AboutView.as_view(), name='about-us'),
    path('contact', ContactView.as_view(), name='contact-us'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

personality/urls.py
from django.urls import path
from personality import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "personality"

urlpatterns = [

    path('index/predict', views.home, name='index'),
    path('index/submit', views.result, name='result'),
 
]

recognition/urls.py
from django.urls import path
from recognition import views
app_name = "recognition"
urlpatterns = [

    path('index/question', views.questions, name='questionPage')

 
]

personality/models.py
# from django.db import models

# class PersonalityPrediction(models.Model):
#     GENDER_CHOICES = (
#         ('Female', 'Female'),
#         ('Male', 'Male'),
#     )

#     gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default='Female')  # Default value set to 'Female'
#     age = models.IntegerField()
#     openness = models.FloatField()
#     neuroticism = models.FloatField()
#     conscientiousness = models.FloatField()
#     agreeableness = models.FloatField()
#     extraversion = models.FloatField()
#     predicted_personality = models.CharField(max_length=50)

#     def __str__(self):
#         return f"{self.gender} - Age: {self.age} - Predicted Personality: {self.predicted_personality}"

personality/views.py
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect , get_object_or_404
from django.views.generic import ListView, DetailView, CreateView
import pandas as pd
from sklearn.preprocessing import StandardScaler
import joblib
import numpy as np
# from tensorflow import keras
# from tensorflow.keras.models import Model
# Create your views here.
reloadModel = joblib.load("./models/train_model.pkl")
scaler = StandardScaler()

def home(request):
    
    return render(request,"personality/index.html")

def result(request):
   
   if request.method == 'POST':
      
      gender = request.POST.get('gender')
      if(gender == "Female"):
        gender_no = 1
      else:
        gender_no = 2
      age = request.POST.get('age')
      openness = request.POST.get('openness')
      neuroticism = request.POST.get('neuroticism')
      conscientiousness = request.POST.get('conscientiousness')
      agreeableness = request.POST.get('agreeableness')
      extraversion = request.POST.get('extraversion')
      result = np.array([gender_no, age, openness,neuroticism, conscientiousness, agreeableness, extraversion], ndmin = 2)
      final = scaler.fit_transform(result)
      print(request)
      personality = str(reloadModel.predict(final)[0])
      context={'personality':personality}
      print(personality)
   return render(request,"personality/submit.html",context)

    

templates/personality/index.html
<!DOCTYPE html>
<html lang="en">
	
<head>
<title>Personality Predict</title>

{% load static %}
<!-- personality template -->
<link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/bootstrap/css/bootstrap.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'personality/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'personality/fonts/iconic/css/material-design-iconic-font.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/animate/animate.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/css-hamburgers/hamburgers.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/animsition/css/animsition.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/select2/select2.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/daterangepicker/daterangepicker.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/daterangepicker/daterangepicker.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'personality/css/util.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'personality/css/main.css' %}">


<!-- nav bar template -->


<link rel="icon" href="{% static 'img/favicon.ico' %}">

<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">

<!-- Icon Font Stylesheet -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

<!-- Libraries Stylesheet -->
 <link rel="stylesheet" href="{% static 'lib/animate/animate.min.css' %}" >
<link rel="stylesheet" href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" >

<!-- Customized Bootstrap Stylesheet-->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 

<!-- Template Stylesheet -->
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> 
<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}">





<style>
	.button
  {
    margin-left: 25%;
    padding-top: 2%;
    padding-bottom: 2%;
    width: 20%;
    border-radius: 40px;
    background-color: #66ff00;
    font-weight: 200;
  }
  .button:hover
  {
    background-color: red;
  }
</style>
</head>




<body>
	<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
		<a href="/" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
			<h1 class="m-0 text-primary">IntelliHire</h1>
		</a>
		<button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<div class="navbar-nav ms-auto p-4 p-lg-0">


		 
				
			   
				 <ul class="navbar-nav ml-auto">
					 <li class="nav-item active">
					<a href="/" class="nav-link">Home <span class="sr-only"></span></a>
				</li>
				<div class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Jobs</a>
					<div class="dropdown-menu rounded-0 m-0">
				<a href="{% url 'jobs:jobs' %}" class="dropdown-item">Job List</a>
						<a href="" class="dropdown-item">Job Detail</a>
					</div>
				</div>  
				<div class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
					<div class="dropdown-menu rounded-0 m-0">
						<a href="{% url 'personality:index' %}" class="dropdown-item">Personality Trait </a>
						<a href="{% url 'recognition:questionPage' %}" class="dropdown-item">Automate Interview</a>
						<a href="{% url 'jobs:about-us' %}" class="dropdown-item">About Us</a>
					</div>
				</div>
			  
				<!-- <li class="nav-item">
					<a href="{% url 'jobs:about-us' %}" class="nav-link">About Us</a>
				</li>  -->
			   
				{% if request.user.is_authenticated and request.user.role == 'employer' %}
					<li class="nav-item dropdown">
						<a id="clientZone" href="#" data-toggle="dropdown"
						   aria-haspopup="true" aria-expanded="false"
						   class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
							<!-- <div class="client-menu-image">
								<div class="inner">
									<img src="{% static 'img/ab.jpg' %}"
										 alt="company image"
										 class="img-fluid">
								</div>
							</div> -->
							{% if request.user.role == 'employee' %}
								{{ request.user.first_name }} {{ request.user.last_name }}
							{% else %}
								{{ request.user.first_name }}
							{% endif %}
						</a>
						<div aria-labelledby="clientZone" class="dropdown-menu">
							<a href="{% url 'jobs:employer-dashboard' %}" class="dropdown-item">Dashboard</a>
							<a href="{% url 'jobs:employer-all-applicants' %}" class="dropdown-item">Applicants </a>
							<a href="{% url 'jobs:employer-jobs-create' %}" class="dropdown-item">Post a new
								job </a>
							<a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
						</div>
					</li>
				{% elif request.user.is_authenticated and request.user.role == 'employee' %}
					<li class="nav-item dropdown">
						<a id="clientZone" href="#" data-toggle="dropdown"
						   aria-haspopup="true" aria-expanded="false"
						   class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
							<!-- <div class="client-menu-image">
								<div class="inner">
									<img src="{% static 'img/ab.jpg' %}"
										 alt="company image"
										 class="img-fluid">
								</div>
							</div> -->
							{% if request.user.role == 'employee' %}
								{{ request.user.first_name }} {{ request.user.last_name }}
							{% else %}
								{{ request.user.first_name }}
							{% endif %}
						</a>
						<div aria-labelledby="clientZone" class="dropdown-menu">
							<a href="{% url 'accounts:employer-profile-update' %}" class="dropdown-item">Edit Profile</a>
							<a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
							
						</div>
					</li>
				{% else %}
					<li class="nav-item dropdown">
						<a id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
						   class="nav-link dropdown-toggle"><i class="fa fa-signing"></i>SignUp
						</a>
						<div aria-labelledby="pages" class="dropdown-menu">
							<a href="{% url 'accounts:employee-register' %}" class="dropdown-item">Job Seekers</a>
							<a href="{% url 'accounts:employer-register' %}" class="dropdown-item">Employers</a>
						</div>
					</li>
				</ul>
			</div>

						<a href="{% url 'accounts:login' %}" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">Login</a>
						</a>
				  
				{% endif %}
			   
				
			
		</div>
	</nav>	
<div class="container-contact100">
<div class="wrap-contact100"> 

<span class="contact100-form-title">
Personality Trait
</span>

<form action="submit" method="POST" class="form">
	{% csrf_token %}
<div class="wrap-input100 bg1" name="gender" data-validate="Please Type Your Gender">
<span class="label-input100">Gender *</span>
<input class="input100" type="text" name="name" placeholder="Enter Your Gender">
</div>

<div class="wrap-input100 rs1-wrap-input100" name="age" data-validate="Enter Your Age (e@a.x)">
<span class="label-input100">Age*</span>
<input class="input100" type="text" name="age" placeholder="Enter Your age ">
</div>

<div class="wrap-input100 input100-select bg1">
<span class="label-input100">Needed Services *</span>
<div>
<select class="js-select2" name="service">
<option>Please chooses</option>
<option>Personality Prediction</option>

</select>
<div class="dropDownSelect2"></div>
</div>
</div>
<div class="w-full dis-none js-show-service">
<div class="wrap-contact100-form-radio">
<span class="label-input100">What type of personality do you belong ?</span>

</div>
<div class="wrap-contact100-form-range">
	
	
	
	
		
		<div class="wrap-input100  bg1 rs1-wrap-input100" >
			<span class="label-input100" >OPENNESS*</span>
			<input class="input100" type="text" name="openness" placeholder="Rate yourself from 1-8 ">
			</div>
			<label class="label-radio100" for="radio1">
				<i></i>
			People who like to learn new things and enjoy new experiences usually score high in openness. 
				</label>
			
			<div class="wrap-input100  bg1 rs1-wrap-input100" >
				<span class="label-input100">NEUROTICISM*</span>
				<input class="input100" type="text" name="neuroticism" placeholder="Rate yourself from 1-8 ">
				</div>
				<label class="label-radio100" for="radio1">
					<i>NOTE:</i>
		Neuroticism or Emotional Stability relates to degree of negative emotions. 
					</label>
				
				<div class="wrap-input100 bg1 rs1-wrap-input100" >
					<span class="label-input100">CONSCIENTIOUSNESS*</span>
					<input class="input100" type="text" name="conscientiousness" placeholder="Rate yourself from 1-8 ">
					</div>
					<label class="label-radio100" for="radio1">
						<i>NOTE:</i>
			People that have a high degree of conscientiousness are reliable and prompt. Traits include being organised, methodic, and thorough.</label>
					
				<div class="wrap-input100 bg1 rs1-wrap-input100" >
					<span class="label-input100">AGREEABLENESS*</span>
					<input class="input100" type="text" name="agreeableness" placeholder="Rate yourself from 1-8 ">
					</div><label class="label-radio100" for="radio1">
						<i>NOTE:</i>
						As it perhaps sounds, these individuals are warm, friendly, compassionate and cooperative and traits include being kind, affectionate, and sympathetic.
					</label>

					
				<div class="wrap-input100 bg1 rs1-wrap-input100" >
					<span class="label-input100">EXTRAVERSION*</span>
					<input class="input100" type="text" name="extraversion" placeholder="Rate yourself from 1-8 ">
					</div><label class="label-radio100" for="radio1">
						<i>NOTE:</i>
			Extraversion traits include being; energetic, talkative, and assertive (sometime seen as outspoken by Introverts). 
						</label>
					
						<input type="submit" name="submit" value="Predict" class="button">

					</div>


</div>


</form>
</div>
</div>
{% load static %}
<script src="{% static 'personality/vendor/jquery/jquery-3.2.1.min.js' %}"></script>

<script src="{% static 'personality/vendor/animsition/js/animsition.min.js' %}"></script>

<script src="{% static 'personality/vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'personality/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'personality/vendor/select2/select2.min.js' %}"></script>
<script src="{% static 'personality/vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'personality/vendor/daterangepicker/daterangepicker.js' %}"></script>

<script src="{% static 'personality/vendor/countdowntime/countdowntime.js' %}"></script>

<script src="{% static 'personality/vendor/noui/nouislider.min.js' %}"></script>

<script src="{% static 'personality/js/main.js'%}"></script>



{% block extra_scripts %}
<script>	
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});


			$(".js-select2").each(function(){
				$(this).on('select2:close', function (e){
					if($(this).val() == "Please chooses") {
						$('.js-show-service').slideUp();
					}
					else {
						$('.js-show-service').slideUp();
						$('.js-show-service').slideDown();
					}
				});
			});
		})
	</script>
{% endblock %}



</html>

templates/personality/submit.html
<!DOCTYPE html>
<html>
<head>
  <title> Personality Prediction Project</title>
  
  {% load static %}

  <link rel="icon" type="image/png" href="{%static 'personality/images/icons/favicon.ico' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/bootstrap/css/bootstrap.min.css' %}">
  
  <link rel="stylesheet" type="text/css" href="{% static 'personality/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
  
  <link rel="stylesheet" type="text/css" href="{% static 'personality/fonts/iconic/css/material-design-iconic-font.min.css' %}">
  
  <link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/animate/animate.css' %}">
  
  <link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/css-hamburgers/hamburgers.min.css' %}">
  
  <link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/animsition/css/animsition.min.css' %}">
  
  <link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/select2/select2.min.css' %}">
  
  <link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/daterangepicker/daterangepicker.css' %}">
  
  <link rel="stylesheet" type="text/css" href="{% static 'personality/vendor/daterangepicker/daterangepicker.css' %}">
  
  <link rel="stylesheet" type="text/css" href="{% static 'personality/css/util.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'personality/css/main.css' %}">

   <!-- nav bar template -->

<link rel="icon" href="{% static 'img/favicon.ico' %}">

<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">

<!-- Icon Font Stylesheet -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

<!-- Libraries Stylesheet -->
 <link rel="stylesheet" href="{% static 'lib/animate/animate.min.css' %}" >
<link rel="stylesheet" href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" >

<!-- Customized Bootstrap Stylesheet-->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 

<!-- Template Stylesheet -->
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> 
<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}">

<style>
  body
  {
   text-align:center;
   width:100%;
   margin:0 auto;
   padding:0px;
   font-family:helvetica;
   background-color:#81DAF5;
  }
  #wrapper
  {
   text-align:center;
   margin:0 auto;
   padding:0px;
   width:995px;
  }
  #image_div
  {
   width:500px;
   margin-left:150px;
   position:relative;
  }
  #image_div img
  {
   width:100%;
  }
  #image_div #image_label
  {
   margin:0px;
   position:absolute;
   bottom:7px;
  }
  #image_div #image_label span
  {
   background-color: #000000;
   opacity:0.8;
   font-size:25px;
   padding:7px;
   box-sizing:border-box;
   color:white;
   font-weight:bold;
  }
  </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
		<a href="/" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
			<h1 class="m-0 text-primary">IntelliHire</h1>
		</a>
		<button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<div class="navbar-nav ms-auto p-4 p-lg-0">


		 
				
			   
				 <ul class="navbar-nav ml-auto">
					 <li class="nav-item active">
					<a href="/" class="nav-link">Home <span class="sr-only"></span></a>
				</li>
				<div class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Jobs</a>
					<div class="dropdown-menu rounded-0 m-0">
				<a href="{% url 'jobs:jobs' %}" class="dropdown-item">Job List</a>
						<a href="" class="dropdown-item">Job Detail</a>
					</div>
				</div>  
				<div class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
					<div class="dropdown-menu rounded-0 m-0">
						<a href="{% url 'personality:index' %}" class="dropdown-item">Personality Trait </a>
						<a href="{% url 'recognition:questionPage' %}" class="dropdown-item">Automate Interview</a>
						<a href="{% url 'jobs:about-us' %}" class="dropdown-item">About Us</a>
					</div>
				</div>
			  
				<!-- <li class="nav-item">
					<a href="{% url 'jobs:about-us' %}" class="nav-link">About Us</a>
				</li>  -->
			   
				{% if request.user.is_authenticated and request.user.role == 'employer' %}
					<li class="nav-item dropdown">
						<a id="clientZone" href="#" data-toggle="dropdown"
						   aria-haspopup="true" aria-expanded="false"
						   class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
							<!-- <div class="client-menu-image">
								<div class="inner">
									<img src="{% static 'img/ab.jpg' %}"
										 alt="company image"
										 class="img-fluid">
								</div>
							</div> -->
							{% if request.user.role == 'employee' %}
								{{ request.user.first_name }} {{ request.user.last_name }}
							{% else %}
								{{ request.user.first_name }}
							{% endif %}
						</a>
						<div aria-labelledby="clientZone" class="dropdown-menu">
							<a href="{% url 'jobs:employer-dashboard' %}" class="dropdown-item">Dashboard</a>
							<a href="{% url 'jobs:employer-all-applicants' %}" class="dropdown-item">Applicants </a>
							<a href="{% url 'jobs:employer-jobs-create' %}" class="dropdown-item">Post a new
								job </a>
							<a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
						</div>
					</li>
				{% elif request.user.is_authenticated and request.user.role == 'employee' %}
					<li class="nav-item dropdown">
						<a id="clientZone" href="#" data-toggle="dropdown"
						   aria-haspopup="true" aria-expanded="false"
						   class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
							<!-- <div class="client-menu-image">
								<div class="inner">
									<img src="{% static 'img/ab.jpg' %}"
										 alt="company image"
										 class="img-fluid">
								</div>
							</div> -->
							{% if request.user.role == 'employee' %}
								{{ request.user.first_name }} {{ request.user.last_name }}
							{% else %}
								{{ request.user.first_name }}
							{% endif %}
						</a>
						<div aria-labelledby="clientZone" class="dropdown-menu">
							<a href="{% url 'accounts:employer-profile-update' %}" class="dropdown-item">Edit Profile</a>
							<a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
							
						</div>
					</li>
				{% else %}
					<li class="nav-item dropdown">
						<a id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
						   class="nav-link dropdown-toggle"><i class="fa fa-signing"></i>SignUp
						</a>
						<div aria-labelledby="pages" class="dropdown-menu">
							<a href="{% url 'accounts:employee-register' %}" class="dropdown-item">Job Seekers</a>
							<a href="{% url 'accounts:employer-register' %}" class="dropdown-item">Employers</a>
						</div>
					</li>
				</ul>
			</div>

						<a href="{% url 'accounts:login' %}" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">Login</a>
						</a>
				  
				{% endif %}
			   
				
			
		</div>
	</nav>	
  <div class="container-contact100">
  <div class="wrap-contact100"> 
    <div id="image_div">
      {% load static %}
      <img src="{% static 'personality/images/personality.jpeg' %}">
      <p id="image_label"><span class="contact100-form-title">PREDICTED PERSONALITY : {{personality}}</span></p>
     </div>
    
   
    </div>
    </div>
</body>
</html>