jobs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),
    path('', include('personality.urls')), 
    path('', include('recognition.urls')),
]

jobsapp/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "jobs"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='search'),
    path('employer/dashboard', include([
        path('', DashboardView.as_view(), name='employer-dashboard'),
        path('all-applicants', ApplicantsListView.as_view(), name='employer-all-applicants'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='employer-dashboard-applicants'),
        path('mark-filled/<int:job_id>', filled, name='job-mark-filled'),
        path('delete/<int:job_id>', delete, name='job-delete'),
    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs', JobListView.as_view(), name='jobs'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('employer/jobs/create', JobCreateView.as_view(), name='employer-jobs-create'),
    path('employer/jobs/edit/<int:pk>', JobUpdateView.as_view(), name='employer-jobs-update'),
    path('upload/', upload_document, name='upload_document'),
    path('about', AboutView.as_view(), name='about-us'),
    path('contact', ContactView.as_view(), name='contact-us'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/jobs/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
About us
{% endblock %}

{% block content %}


    <!-- Header End -->
        <div class="container-xxl py-5 bg-dark page-header mb-5">
            <div class="container my-5 pt-5 pb-4">
                <h1 class="display-3 text-white mb-3 animated slideInDown">About Us</h1>
            </div>
        </div>
        <!-- Header End -->

        <!-- About Start -->
        <div class="container-xxl py-5">
            <div class="container">
                <div class="row g-5 align-items-center">
                    <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                        <div class="row g-0 about-bg rounded overflow-hidden">
                            <div class="col-6 text-start">
                                <img class="img-fluid w-100" src="{% static 'img/about-1.jpg' %}">
                            </div>
                            <div class="col-6 text-start">
                                <img class="img-fluid" src="{% static 'img/about-2.jpg' %}" style="width: 85%; margin-top: 15%;">
                            </div>
                            <div class="col-6 text-end">
                                <img class="img-fluid" src="{% static 'img/about-3.jpg' %}" style="width: 85%;">
                            </div>
                            <div class="col-6 text-end">
                                <img class="img-fluid w-100" src="{% static 'img/about-4.jpg' %}">
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                        <h1 class="mb-4">We Help To Get The Best Job And Find A Talent</h1>
                        <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Tempor erat elitr rebum at clita</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Aliqu diam amet diam et eos</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Clita duo justo magna dolore erat amet</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Clita duo justo magna dolore erat amet</p>

                        <p><i class="fa fa-check text-primary me-3"></i>Clita duo justo magna dolore erat amet</p>
                        
                       
                    </div>
                </div>
            </div>
        </div>
        <!-- About End -->

        {% endblock %}
      

templates/jobs/details.html
{% extends 'base.html' %}
{% load static %}
{% load is_already_applied %}
{% block title %}
    Job details
{% endblock %}

{% block content %}
    
      

        <!-- Job Detail Start -->
        <div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
            <div class="container">
                <div class="row gy-5 gx-4">
                    <div class="col-lg-8">
                        <div class="d-flex align-items-center mb-5">
                            <img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-2.jpg" alt="" style="width: 80px; height: 80px;">
                            <div class="text-start ps-4">
                                <h3 class="mb-3">{{ job.title }} <small>at <a href="#"> {{ job.company_name }}</a></small></h3>
                                
                
                                <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i> {{ job.location }}</span>
                                <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>{{ job.created_at|timesince }}</span>
                                <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>
                            </div>  
                        </div>

                        <div class="mb-5">
                            <h4 class="mb-3">Job description</h4>
                            <p>{{ job.description }}</p>
                            <h4 class="mb-3">Responsibility</h4>
                            <p>Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor</p>
                            <ul class="list-unstyled">
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Dolor justo tempor duo ipsum accusam</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Elitr stet dolor vero clita labore gubergren</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Rebum vero dolores dolores elitr</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Est voluptua et sanctus at sanctus erat</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Diam diam stet erat no est est</li>
                            </ul>
                            <h4 class="mb-3">Qualifications</h4>
                            <p>Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor</p>
                            <ul class="list-unstyled">
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Dolor justo tempor duo ipsum accusam</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Elitr stet dolor vero clita labore gubergren</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Rebum vero dolores dolores elitr</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Est voluptua et sanctus at sanctus erat</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Diam diam stet erat no est est</li>
                            </ul>
                        </div>
        
                        <div class="">
                            <h4 class="mb-4">Apply For The Job</h4>
                            <form>
                                <div class="row g-3">
                                    <div class="col-12 col-sm-6">
                                        <input type="text" class="form-control" placeholder="Your Name">
                                    </div>
                                    <div class="col-12 col-sm-6">
                                        <input type="email" class="form-control" placeholder="Your Email">
                                    </div>
                                    <div class="col-12 col-sm-6">
                                        <input type="text" class="form-control" placeholder="Portfolio Website">
                                    </div>
                                    <div class="col-12 col-sm-6">
                                        <input type="file" class="form-control bg-white">
                                    </div>
                                    <div class="col-12">
                                        <textarea class="form-control" rows="5" placeholder="Coverletter"></textarea>
                                    </div>
                                    
                                </div>
                            </form>
                        </div>
                        <div class="col-12">
                            {% if request.user.is_authenticated %}
                                {% is_already_applied job request.user as is_applied %}
                                {% if is_applied %}
                                    <input type="button" class="btn btn-outline-white-primary" value="Already applied"/>
                                {% else %}
                                    <form action="{% url 'jobs:apply-job' job.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="job" value="{{ job.id }}">
                                        <input type="submit" class="btn btn-success"
                                               value="Apply for this job"/>
                                    </form>
                                {% endif %}
                            {% else %}
                                <form action="{% url 'jobs:apply-job' job.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="job" value="{{ job.id }}">
                                    <button class="btn btn-primary w-100" type="submit">Apply Now</button>
                                </form>
                            {% endif %}
                        </div>
                        
                    </div>
        
                    <div class="col-lg-4">
                        <div class="bg-light rounded p-5 mb-4 wow slideInUp" data-wow-delay="0.1s">
                            <h4 class="mb-4">About {{ job.company_name }}</h4>
                            <p class="m-0">{{ job.company_description }}</p>
                            <p class="job-detail__social social social--outline">
                                <a href="{{ job.website }}" data-toggle="tooltip" data-placement="top" title="Website"
                                   class="link">
                                    <i class="fa fa-link"></i>
                                </a>
                                <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter" class="twitter">
                                    <i class="fa fa-twitter"></i>
                                </a>
                                <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook" class="facebook">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </p>
                        </div>
                        
                        <div class="bg-light rounded p-5 wow slideInUp" data-wow-delay="0.1s">
                            <h4 class="mb-4">Job Summary</h4>
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Posted: {{ job.created_at|timesince }}</p>
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Vacancy: 123 Position</p>
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Job Nature: Full Time</p>
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Salary: $123 - $456</p>
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Location: {{ job.location }} </p>
                            <p class="m-0"><i class="fa fa-angle-right text-primary me-2"></i>Deadline: {{ job.last_date|date }}</p>
                        </div>

                        
                    </div>
                </div>
            </div>
        </div>
        <!-- Job Detail End -->


       

        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    
    {% endblock %}

templates/jobs/jobs.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    All jobs
{% endblock %}

{% block content %}
 <!-- Header End -->
 <div class="container-xxl py-5 bg-dark page-header mb-5">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Job List</h1>
    </div>
</div>
<!-- Header End -->
    <section class="job-form-section job-form-section--compressed">
        <div class="container">
            <h3 class="heading">Find a <span class="accent">job </span> that will <span class="accent">fit to your experties</span></h4>
           <!-- Search Start -->
    <div class="container-fluid bg-primary mb-5 wow fadeIn" data-wow-delay="0.1s" style="padding: 35px;">
        
        <div class="container">
            <div class="row g-2">
                            <div class="col-md-10">
                                 <form id="job-main-form" method="get" action="{% url 'jobs:search' %}" class="job-main-form">
                            
                                 
                                <div class="row g-2">
                                    <div class="col-md-4">
                                    

                                <input type="text" class="form-control border-0" placeholder="Keyword" />
                                        
                                    </div>
                                    <div class="col-md-4">
                                
                                            <input type="text" id="profession" name="position"
                                                   placeholder="Position"  style="color: black" class="form-control border-0">
                                                   
                                    </div>

                                    <div class="col-md-4">
                                           
                                            <input type="text" id="location" name="location"
                                                   placeholder="Location" class="form-control border-0">
                                    </div>
                                </div>
                                
                            </div>
                                    
                                    <div class="col-md-2">
                                        <button type="submit"
                                                class="btn btn-dark border-0 w-100">Search
                                           
                                        </button>
                                    </div>
                                
                            
                        </form>


            </div>
        </div>
    </div>
    
        </div>
    </section>
    <section>
         <div class="container">
            <h4 class="heading">We have found <span class="accent">{{ jobs.count }}</span> jobs</h3>
            {% for job in jobs %}
            <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
                <div class="tab-content">
                 <div id="tab-1" class="tab-pane fade show p-0 active">
                   
                            <div class="job-item p-4 mb-4">
                                <div class="row g-4">
                                    <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                        <!-- <img class="flex-shrink-0 img-fluid border rounded" src="{% static 'img/abc.jpg' %}" alt="" style="width: 80px; height: 80px;"> -->
                                        
                                    <div class="text-start ps-4">
                                        <h5 class="mb-3">
                                            <a href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a>
                                        </h5>
                                        <p class="job__company">
                                            {{ job.company_name }}
                                        </p>
                                        <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i> {{ job.location }}</span>
                                        <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>{{job.created_at|timesince }}</span>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                    <div class="d-flex mb-3">
                                        <a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>
                                        <a class="btn btn-primary" href="">Apply Now</a>
                                    </div>
                                    <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>DeadLine: {{ job.last_date }}</small>
                                </div>
    
                            </div>
                            
                          
                        </div>
            {% endfor %}
            {% if is_paginated %}
                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}"
                                           class="page-link">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&laquo;</a>
                                    </li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link">{{ i }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>

{% endblock %}

templates/jobs/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    All jobs
{% endblock %}

{% block content %}

   
   <!-- Search Start -->
   <div class="container-fluid bg-primary mb-5 wow fadeIn" data-wow-delay="0.1s" style="padding: 35px;">
        
    <div class="container">
        <div class="row g-2">
                        <div class="col-md-10">
                             <form id="job-main-form" method="get" action="{% url 'jobs:search' %}" class="job-main-form">
                        
                             
                            <div class="row g-2">
                                <div class="col-md-4">
                                

                            <input type="text" class="form-control border-0" placeholder="Keyword" />
                                    
                                </div>
                                <div class="col-md-4">
                            
                                        <input type="text" id="profession" name="position"
                                               placeholder="Position"  style="color: black" class="form-control border-0">
                                               
                                </div>

                                <div class="col-md-4">
                                       
                                        <input type="text" id="location" name="location"
                                               placeholder="Location" class="form-control border-0">
                                </div>
                            </div>
                            
                        </div>
                                
                                <div class="col-md-2">
                                    <button type="submit"
                                            class="btn btn-dark border-0 w-100">Search
                                       
                                    </button>
                                </div>
                            
                        
                    </form>


        </div>
    </div>
</div>

    
    <section>
        <div class="container">
            <h3 class="heading">We have found <span class="accent">{{ jobs.count }}</span> jobs</h3>
            {% for job in jobs %}
            <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
                <div class="tab-content">
                 <div id="tab-1" class="tab-pane fade show p-0 active">
                   
                            <div class="job-item p-4 mb-4">
                                <div class="row g-4">
                                    <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                        <!-- <img class="flex-shrink-0 img-fluid border rounded" src="{% static 'img/abc.jpg' %}" alt="" style="width: 80px; height: 80px;"> -->
                                        
                                    <div class="text-start ps-4">
                                        <h5 class="mb-3">
                                            <a href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a>
                                        </h5>
                                        <p class="job__company">
                                            {{ job.company_name }}
                                        </p>
                                        <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i> {{ job.location }}</span>
                                        <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>{{job.created_at|timesince }}</span>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                    <div class="d-flex mb-3">
                                        <a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>
                                        <a class="btn btn-primary" href="">Apply Now</a>
                                    </div>
                                    <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>DeadLine: {{ job.last_date }}</small>
                                </div>
    
                            </div>
                            
                          
                        </div>
            {% endfor %}
            {% if is_paginated %}
                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}"
                                           class="page-link">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&laquo;</a>
                                    </li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link">{{ i }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>

{% endblock %}